name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "test"
database_id = "f9cef2b8-6790-480b-9a9a-d6072f9c5f9e"

[version_metadata]
binding = "CF_VERSION_METADATA"
